
###
POST http://localhost:8080/v1/proposals
Content-Type: application/json
X-Correlation-ID: {{$random.uuid}}

{
  "metadata": {
    "account_id": "{{$random.uuid}}",
    "offer_opt_in": true
  },
  "personId": "{{$random.uuid}}",
  "processId": "{{$random.uuid}}",
  "statusId": "3c94fc10-a9e9-4546-b298-68417b379a1e",
  "intentionId": "42e195e9-d107-4c65-acb1-04fd82afd099"
}
> {%
  client.global.set("proposalId", response.body.data.id)
%}

###
PATCH http://localhost:8080/v1/proposals/3d9689b7-c445-4cb1-98ff-dd7419e7d2f9
Content-Type: application/json
X-Correlation-ID: {{$random.uuid}}

{
  "metadata": {
  },
  "statusId": "{{$random.uuid}}"
}

###
GET http://localhost:8080/v1/proposals/{{proposalId}}
X-Correlation-ID: {{$random.uuid}}

> {%
  client.assert(response.status == 200)
%}

###
< {%
    let metadataSearch = {
        "$.account_id": [
            "d62fcd2a-c4f9-4713-b906-f1343212023c",
            "4f7c2f8e-692f-40ed-8a9a-98b9caca5415",
        ],
    };
    metadataSearch = {}
    request.variables.set("metadataSearch", encodeURIComponent(JSON.stringify(metadataSearch)));
%}
GET http://localhost:8080/v1/proposals?size=3&page=0&metadata={{metadataSearch}}&statusId=3c94fc10-a9e9-4546-b298-68417b379a1e&processId=77041a11-8e64-4c16-add3-ce777ad2f14f
X-Correlation-ID: {{$random.uuid}}

> {%
    var arr = new Array(response.body.data.items)
    var s = arr.length > 0
    client.assert(s, "Lista")
%}

###
DELETE http://localhost:8080/v1/proposals/{{proposalId}}
X-Correlation-ID: {{$random.uuid}}

###